version: '3.5'

services:
  db:
    container_name: library_db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=kapitonov
    image: postgres